### ISSUE TITLE
Initial integration tests

### ISSUE THREAD

**Issue by TomNicholas** [xarray-contrib/cubed-xarray#4]
So far I've only been testing this package locally, but we need some integration tests, if only to [satisfy conda-forge](https://github.com/conda-forge/staged-recipes/pull/22784#issuecomment-1540601088).

In future we should use https://github.com/pydata/xarray/issues/6894 to expand into a full suite of tests that run in this repo's CI.

**Comment by keewis** [comment]
> if only to satisfy conda-forge

note that the tests for `pint-xarray` (and any of the other packages I have) just make sure the version is correct.
